### ISSUE TITLE
Axes/Position 1mm Step

### ISSUE THREAD

**Issue by SamNitro** [seho85/klipper-dgus#45]
Hey, unter Axes/Position kann ich den "1" mm step nicht anwählen. Die anderen Funktionieren

Gruß Patrick

**Comment by seho85** [comment]
Hi,

problem is fixed. You need to reflash your display. I keep this issue open and waiting for feedback.

Thanks for reporting.

**Comment by SamNitro** [comment]
Ja Funktioniert jetzt, ich mache dann hier zu.

Danke für deine Arbeit
