### ISSUE TITLE
Add support for moonraker update_manager

### ISSUE THREAD

**Issue by besanur** [seho85/klipper-dgus#58]
Please add support for moonraker update_manager

https://moonraker.readthedocs.io/en/latest/configuration/#update_manager

**Comment by seho85** [comment]
I already made a few tests with the moonraker update_manager, and it's generally working - but it have one major caveat: Updating the DGUS display. 

The update_manager just allows pulling new git sources, but this may lead to discrepancies between display application (DGUS project) currently flashed to the display and python sources. Also I haven't used any git tags for now, which were required by the moonraker update_manager.

I'm currently working on an "About" page that shows the versions on the display application, the python sources and the python library that is used for communicating to the display. Adding this feature also requires git tagging.

That would at least allow to show the user per display that the display needs to be updated. I would prefer if i get it managed somehow, to show a notification (bell icon in the webui) when the display needs to be updated. But currently I got no idea, how the get to this information.
